### PR TITLE
build: bump hadolint to v2.8.0

### PR DESCRIPTION
**Pull request by offa**
Bumps hadolint to latest v2.8.0 version.

### CODE REVIEW

**Comment by machisuke** [comment]
@lorenzo
Hi, we look forward to this PR being merged!

**Comment by offa** [comment]
ping @lorenzo

**Comment by lorenzo** [comment]
sorry, I was on a long leave. I'm back :)

**Comment by offa** [comment]
Thanks!

**Comment by offa** [comment]
@lorenzo can we have a new release in the near future so we can use the new version?

**Comment by lorenzo** [comment]
I just released a new version @offa

Sorry for the long wait

**Pull request closed without merging**
